### ISSUE TITLE
企业付款到零钱的API中partner_key参数指的是什么？

### ISSUE THREAD

**Issue by devoutDisciple** [klover2/node-wxpay#1]
版本：node-wxpay3@1.1.4

const wxwithdeaw = new WxWithdraw({
    'partner_key': '', // key为商户平台设置的密钥key
    'pfx': fs.readFileSync('./apiclient_cert.p12'),
});
企业付款到零钱的功能中，传的参数中的partner_key字段指的是apiv2密钥还是apiv3密钥？希望您能解答一下

**Comment by devoutDisciple** [comment]
还有一个就是
const options = {
            'mch_appid': 'appid',
            'mchid': '商户id',
            'partner_trade_no': '',
            'openid': 'openid',
            'check_name': 'NO_CHECK',
            'amount': 1,
            'desc': '提现到零钱测试',
        };
        const result = await wxwithdeaw.transfers(options);

传入参数中的partner_trade_no指的是什么

**Comment by klover2** [comment]
partner_key 是 apiv2，这个npm 使用的都是微信支付旧版接口

**Comment by klover2** [comment]
partner_key 是 apiv2，这个npm包 使用的都是微信支付旧版接口

**Comment by klover2** [comment]
partner_trade_no是你自己这边自定义订单号，参考文档 https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=14_2

**Comment by klover2** [comment]
我文档里面都配置了链接，可以点击查看
